title: LEO's Blog
description: Personal website of Dr. Fu Li, expert in AI infrastructure networking
baseurl: "" # if your site is in a subdirectory, put it here
url: "https://leoustc.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Dr. Fu Li"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor