title: Dr. Fu Li (Leo)
description: Personal website of Dr. Fu Li, expert in AI infrastructure networking
baseurl: "" # if your site is in a subdirectory, put it here
url: "https://leoustc.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Dr. Fu Li"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 